name: UNIT

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: install openssl
        if: matrix.os == 'windows-latest'
        run: vcpkg integrate install && vcpkg install openssl:x64-windows-static-md
      - name: Cargo test
        run: cargo test